packages:
  - .
  - docs
catalog:
  '@codemirror/lang-json': ^6.0.1
  '@codemirror/lang-xml': ^6.1.0
  '@codemirror/language': ^6.11.0
  '@codemirror/state': ^6.5.2
  '@codemirror/view': ^6.36.8
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/lucide': ^1.2.44
  '@lezer/highlight': ^1.2.1
  '@ntnyq/eslint-config': ^4.3.0
  '@ntnyq/prettier-config': ^2.2.0
  '@ntnyq/utils': ^0.7.0
  '@shikijs/transformers': ^3.4.2
  '@shikijs/vitepress-twoslash': ^3.4.2
  '@types/node': ^22.15.21
  '@uiw/codemirror-themes': ^4.23.12
  '@vitest/coverage-v8': ^3.1.4
  '@vueuse/core': ^13.2.0
  bumpp: ^10.1.1
  codemirror: ^6.0.1
  eslint: ^9.27.0
  eslint-visitor-keys: ^4.2.0
  floating-vue: ^5.2.2
  husky: ^9.1.7
  nano-staged: ^0.8.0
  npm-run-all2: ^8.0.4
  prettier: ^3.5.3
  splitpanes: ^4.0.4
  twoslash: ^0.3.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.2
  unplugin-vue-components: ^28.7.0
  vite: ^6.3.5
  vitepress: ^2.0.0-alpha.5
  vitepress-plugin-group-icons: ^1.5.5
  vitest: ^3.1.4
  vue: ^3.5.14
  vue-codemirror: ^6.1.1
overrides:
  esbuild: ^0.25.4
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
