packages:
  - .
  - docs
catalog:
  '@codemirror/lang-json': ^6.0.1
  '@codemirror/lang-xml': ^6.1.0
  '@codemirror/language': ^6.11.0
  '@codemirror/state': ^6.5.2
  '@codemirror/view': ^6.36.7
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/lucide': ^1.2.40
  '@lezer/highlight': ^1.2.1
  '@ntnyq/eslint-config': ^4.1.0
  '@ntnyq/prettier-config': ^2.0.0
  '@ntnyq/utils': ^0.6.4
  '@shikijs/transformers': ^3.4.0
  '@shikijs/vitepress-twoslash': ^3.4.0
  '@types/node': ^22.15.14
  '@uiw/codemirror-themes': ^4.23.12
  '@vitest/coverage-v8': ^3.1.3
  '@vueuse/core': ^13.1.0
  bumpp: ^10.1.0
  codemirror: ^6.0.1
  eslint: ^9.26.0
  eslint-visitor-keys: ^4.2.0
  floating-vue: ^5.2.2
  husky: ^9.1.7
  nano-staged: ^0.8.0
  npm-run-all2: ^8.0.1
  prettier: ^3.5.3
  twoslash: ^0.3.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.0
  unplugin-vue-components: ^28.5.0
  vite: ^6.3.5
  vitepress: ^2.0.0-alpha.5
  vitepress-plugin-group-icons: ^1.5.2
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-codemirror: ^6.1.1
  vue-resizable-panels: ^0.0.1
overrides:
  esbuild: ^0.25.2
onlyBuiltDependencies:
  - esbuild
patchedDependencies:
  vue-resizable-panels: patches/vue-resizable-panels.patch
