export enum NodeTypes {
  Attribute = 'Attribute',
  AttributeKey = 'AttributeKey',
  AttributeValue = 'AttributeValue',
  Comment = 'Comment',
  Doctype = 'Doctype',
  DoctypeAttribute = 'DoctypeAttribute',
  DoctypeAttributeValue = 'DoctypeAttributeValue',
  Document = 'Document',
  Element = 'Element',
  Error = 'Error',
  Program = 'Program',
  /** @deprecated Use Element instead. */
  Tag = 'Element',
  Text = 'Text',
  XMLDeclaration = 'XMLDeclaration',
  XMLDeclarationAttribute = 'XMLDeclarationAttribute',
  XMLDeclarationAttributeKey = 'XMLDeclarationAttributeKey',
  XMLDeclarationAttributeValue = 'XMLDeclarationAttributeValue',
}
