/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionContainer: typeof import('./.vitepress/components/Playground/ActionContainer.vue')['default']
    AstViewer: typeof import('./.vitepress/components/ast/AstViewer.vue')['default']
    CodeContainer: typeof import('./.vitepress/components/Playground/CodeContainer.vue')['default']
    CopyButton: typeof import('./.vitepress/components/ui/CopyButton.vue')['default']
    DataRender: typeof import('./.vitepress/components/ast/DataRender.vue')['default']
    DropZone: typeof import('./.vitepress/components/DropZone.vue')['default']
    Editor: typeof import('./.vitepress/components/Editor/index.vue')['default']
    HiddenItem: typeof import('./.vitepress/components/ast/HiddenItem.vue')['default']
    InputContainer: typeof import('./.vitepress/components/Playground/InputContainer.vue')['default']
    JsonArray: typeof import('./.vitepress/components/ast/JsonArray.vue')['default']
    JsonContainer: typeof import('./.vitepress/components/Playground/JsonContainer.vue')['default']
    JsonIterable: typeof import('./.vitepress/components/ast/JsonIterable.vue')['default']
    JsonObject: typeof import('./.vitepress/components/ast/JsonObject.vue')['default']
    JsonPrimitiveValue: typeof import('./.vitepress/components/ast/JsonPrimitiveValue.vue')['default']
    OutputContainer: typeof import('./.vitepress/components/Playground/OutputContainer.vue')['default']
    Playground: typeof import('./.vitepress/components/Playground/index.vue')['default']
    PreviewContainer: typeof import('./.vitepress/components/Playground/PreviewContainer.vue')['default']
    PropertyLink: typeof import('./.vitepress/components/ast/PropertyLink.vue')['default']
    PropertyName: typeof import('./.vitepress/components/ast/PropertyName.vue')['default']
    PropertyValue: typeof import('./.vitepress/components/ast/PropertyValue.vue')['default']
    README: typeof import('./.vitepress/components/ast/README.md')['default']
    RenderExpandableObject: typeof import('./.vitepress/components/ast/RenderExpandableObject.vue')['default']
    TabItem: typeof import('./.vitepress/components/ui/TabItem.vue')['default']
    Tabs: typeof import('./.vitepress/components/ui/Tabs.vue')['default']
    TreeContainer: typeof import('./.vitepress/components/Playground/TreeContainer.vue')['default']
  }
}
