/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AstContainer: typeof import('./.vitepress/components/Playground/AstContainer.vue')['default']
    CodeContainer: typeof import('./.vitepress/components/Playground/CodeContainer.vue')['default']
    Editor: typeof import('./.vitepress/components/Editor/index.vue')['default']
    InputContainer: typeof import('./.vitepress/components/Playground/InputContainer.vue')['default']
    OutputContainer: typeof import('./.vitepress/components/Playground/OutputContainer.vue')['default']
    Playground: typeof import('./.vitepress/components/Playground/index.vue')['default']
  }
}
